import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';
import styles from 'scss/Home.module.css';
import Link from 'next/link';
import { useRouter } from 'next/dist/client/router';
import { useEffect } from 'react';

const Home: NextPage = () => {
  const router = useRouter();
  useEffect(() => {
    // Always do navigations after the first render
    router.push('/Login?slug=post.slug', undefined, { shallow: true })
  }, [])

  useEffect(() => {
    // The counter changed!
  }, [router.query.counter])
  return (
    <div className={styles.container}>
      <Head>
        <title>cex-app</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge,chrome=1" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" />
        <link href="https://fonts.googleapis.com/css2?family=Inter&display=optional" rel="stylesheet" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap" />
      </Head>
      <>
        <Script id="google-analytics" src={`https://www.google-analytics.com/analytics.js`} />
      </>

      <main className={styles.main}>
        <div className={styles.grid}>
          <Link href="/">
            <a>Home</a>
          </Link>
          <Link href={{ pathname: '/Login', query: { slug: "post.slug" }, }}>
            <a>Home</a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  );
};

export default Home;
