import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Script from 'next/script';
import styles from '../styles/Home.module.css';
import Link from 'next/link';

const Home: NextPage = () => {

  return (
    <div className={styles.container}>
      <Head>
        <title>cex-app</title>
        <meta name="description" content="Generated by create next app"/>
        <meta charSet="utf-8"/>
        <meta httpEquiv="X-UA-Compatible" content="IE=edge,chrome=1"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
        <link rel="icon" href="/favicon.ico"/>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter&display=optional"
          rel="stylesheet"
        />
      </Head>
      <>
        <Script id="google-analytics" src={`https://www.google-analytics.com/analytics.js`}/>
        <Script
          id="axios" src={`https://unpkg.com/axios/dist/axios.min.js`}/>
      </>
      <main className={styles.main}>
        <>
        </>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <Link href="/">
            <a>Home</a>
          </Link>
          <Link href={{
            pathname: '/login',
            query: { slug: "post.slug" },
          }}>
            <a>Home</a>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16}/>
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
